FROM emscripten/emsdk:latest

USER root

# 1. Create the system-level bits directory
RUN mkdir -p /emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/bits

# 2. Copy stdc++.h from host into the container's standard library path
COPY inner/bits/stdc++.h /emsdk/upstream/emscripten/cache/sysroot/include/c++/v1/bits/stdc++.h


# Create temp directory
# RUN mkdir /temp \
#     && chown sandbox_user:sandbox_user /temp \
#     && chmod 700 /temp

RUN useradd -m -s /bin/bash sandbox_user

RUN chown -R sandbox_user:sandbox_user /emsdk/upstream/emscripten/cache \
    && chmod -R 755 /emsdk/upstream/emscripten/cache

# COPY entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh

# # 4. Pre-compile and warm up the system cache to reduce write overhead at runtime
# RUN embuilder build sysroot

# # 5. Switch to a non-root user, fully dropping superuser privileges
USER sandbox_user

# 6. Set the default working directory
WORKDIR /src

# ENTRYPOINT ["/entrypoint.sh"]

CMD ["/bin/bash"]